http://localhost:8080/message
###

http://localhost:8080/messages
####

http://localhost:8080/messages/2
####

http://localhost:8080/bySender/Will
###

POST http://localhost:8080/addMessage
Content-Type: application/json

{
    "messageContent":"Bryan's Song 3",
    "sender": {
      "email" : "me@here",
      "name" : "Bryan"
    }
}
###

POST http://localhost:8080/addperson
Content-Type: application/json

{
  "name" : "Dimmy",
  "email" : "her@there"
}